server:
  port: 8999

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: HikariPoolModbd
    username: sys
    password: root
    url: jdbc:oracle:thin:@//localhost:11523/ORCLPDB1
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false