server:
  port: 8999

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: HikariPoolModbd
    username: modbd
    password: oracle
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb1.localdomain
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false